version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespassword"
    ports:
      - "5432:5432"
