logging:
  level:
    root: INFO
#    com.alexahdp.spring.database.pool: INFO
  file:
    name: app.log
    path: /logs
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
