logging:
  level:
    root: INFO
#    com.alexahdp.spring.database.pool: INFO
    com.springframework.jdbc.core: DEBUG
  file:
    name: app.log
    path: /logs
spring:
  app:
    image:
      bucket: users-images
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
